blog_index:
    path: /
    defaults: { _controller: App\Controller\WelcomeController }
    methods: GET|HEAD

blog_post_list:
    path: /post_list
    defaults: { _controller: App\Controller\Post\ListController }
    methods: GET|POST



blog_post:
    path: /post/{id}
    defaults: { _controller: App\Controller\Post\GetController }
    methods: GET

blog_post_new:
    path: /post_new
    defaults: { _controller: App\Controller\Post\NewController }
    methods: GET|POST

blog_post_update:
    path: /post_update/{id}
    defaults: { _controller: App\Controller\Post\UpdateController }
    methods: GET|POST
